name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # or any other branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Zip the Lambda function
        run: |
          zip -r ./PullShipmentJobData.zip ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code --function-name PullShipmentJobData --zip-file fileb://lambda_function.zip
